-- MySQL Script generated by MySQL Workbench
-- 10/04/15 10:56:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `University` ;

-- -----------------------------------------------------
-- Table `University`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Faculties` (
  `FacultyId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`FacultyId`)  COMMENT '',
  UNIQUE INDEX `FacultyId_UNIQUE` (`FacultyId` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Departments` (
  `DepartmentId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `FacultyId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`DepartmentId`)  COMMENT '',
  UNIQUE INDEX `DepartmentId_UNIQUE` (`DepartmentId` ASC)  COMMENT '',
  INDEX `fk_Departments_Faculties_idx` (`FacultyId` ASC)  COMMENT '',
  CONSTRAINT `fk_Departments_Faculties`
    FOREIGN KEY (`FacultyId`)
    REFERENCES `University`.`Faculties` (`FacultyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `University`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Professors` (
  `ProfessorId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `DepartmentId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ProfessorId`)  COMMENT '',
  UNIQUE INDEX `ProfessorId_UNIQUE` (`ProfessorId` ASC)  COMMENT '',
  INDEX `fk_Professors_Departments1_idx` (`DepartmentId` ASC)  COMMENT '',
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `University`.`Departments` (`DepartmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Titles` (
  `TitleId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `ProfessorId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`TitleId`)  COMMENT '',
  UNIQUE INDEX `TitleId_UNIQUE` (`TitleId` ASC)  COMMENT '',
  INDEX `fk_Titles_Professors1_idx` (`ProfessorId` ASC)  COMMENT '',
  CONSTRAINT `fk_Titles_Professors1`
    FOREIGN KEY (`ProfessorId`)
    REFERENCES `University`.`Professors` (`ProfessorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Courses` (
  `CourseId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `ProfessorId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`CourseId`)  COMMENT '',
  UNIQUE INDEX `CourseId_UNIQUE` (`CourseId` ASC)  COMMENT '',
  INDEX `fk_Courses_Professors1_idx` (`ProfessorId` ASC)  COMMENT '',
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`ProfessorId`)
    REFERENCES `University`.`Professors` (`ProfessorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Students` (
  `StudentId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `FaciltyId` INT NOT NULL COMMENT '',
  `DepartmentId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`StudentId`)  COMMENT '',
  UNIQUE INDEX `StudentId_UNIQUE` (`StudentId` ASC)  COMMENT '',
  INDEX `fk_Students_Faculties1_idx` (`FaciltyId` ASC)  COMMENT '',
  INDEX `fk_Students_Departments1_idx` (`DepartmentId` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`FaciltyId`)
    REFERENCES `University`.`Faculties` (`FacultyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Departments1`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `University`.`Departments` (`DepartmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`StudentsCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`StudentsCourses` (
  `StudentId` INT NOT NULL COMMENT '',
  `CourseId` INT NOT NULL COMMENT '',
  INDEX `fk_StudentsCourses_Students1_idx` (`StudentId` ASC)  COMMENT '',
  INDEX `fk_StudentsCourses_Courses1_idx` (`CourseId` ASC)  COMMENT '',
  CONSTRAINT `fk_StudentsCourses_Students1`
    FOREIGN KEY (`StudentId`)
    REFERENCES `University`.`Students` (`StudentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentsCourses_Courses1`
    FOREIGN KEY (`CourseId`)
    REFERENCES `University`.`Courses` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
