ALTER TABLE Users
ADD GroupId int
GO

INSERT INTO Groups VALUES('GROUP1')
INSERT INTO Groups VALUES('GROUP2')
INSERT INTO Groups VALUES('GROUP3')
INSERT INTO Groups VALUES('GROUP4')
INSERT INTO Groups VALUES('GROUP5')

GO

ALTER TABLE USERS
ADD CONSTRAINT FK_GroupId FOREIGN KEY (GroupId) REFERENCES Groups(GroupId)
GO